// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Construct DATABASE_URL from environment variables if not set
const databaseUrl = process.env.DATABASE_URL || 
  `postgresql://${process.env.AUTH_DATABASE_USER}:${process.env.AUTH_DATABASE_PASSWORD}@${process.env.AUTH_DATABASE_HOST}:${process.env.AUTH_DATABASE_PORT}/${process.env.AUTH_DATABASE_NAME}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
